Iteration 1
nivanov045/gofermart pull request #3
Opened 2022-09-30 07:03 UTC by nivanov045

2022-10-04 10:37 UTC, rktkov requested changes

2022-10-04 10:37 UTC, rktkov commented on cmd/gophermart/accrualsystem/accrualsystem.go
> +			go a.getAccrual(a.ordersToProcess[0])
А не возникает тут ситуации "дедлока"
1. на строке 38 мутекс "взводится"
2. на 41 запускается горутина отправки на сервис
3. а внутри горутины происходят попытки опять заблокировать мютекс (строка 107, 115 и т.д., везде где возможна ошибка обработки)
Я бы переделал способ обмена информацией между горутинами с использования "общей памяти" (слайс ordersToProcess) на канал.

2022-10-04 10:37 UTC, rktkov commented on internal/order/order.go
> +type Interface struct {
Не понятно зачем дублировать структуру, совпадающую по полям с уже существующей (Order).

2022-10-04 10:37 UTC, rktkov commented on internal/withdraw/withdraw.go
> +type Interface struct {
Не понятно зачем дублировать структуру, совпадающую по полям с уже существующей (Withdraw).

2022-10-06 12:10 UTC, rktkov approved these changes
Все выглядит отлично! Если есть какие-то вопросы или сомнения, которые бы хотелось задать или поделиться, лучше это сделать на 1-1. Договориться можно через личку слака.

2022-10-08 08:58 UTC, nivanov045 commented on internal/withdraw/withdraw.go
> +type Interface struct {
Отличие в типе поля `sum`. В `Withdraw` оно `int64`, чтобы хранить суммы в минимальной единице. А в интерфейсе `float64`, так как этого требует контракт с клиентом.

2022-10-08 08:58 UTC, nivanov045 commented on internal/order/order.go
> +type Interface struct {
Отличие в типе поля `sum`. В `Order` оно `int64`, чтобы хранить суммы в минимальной единице. А в интерфейсе `float64`, так как этого требует контракт с клиентом.

2022-10-08 12:42 UTC, nivanov045 commented on cmd/gophermart/accrualsystem/accrualsystem.go
> +			go a.getAccrual(a.ordersToProcess[0])
Поправил

2022-10-13 08:38 UTC, rktkov approved these changes

2023-04-06 15:25 UTC, merged